[general]
import = [
    "~/.config/alacritty/themes/custom.toml"
]

[font]
size = 14.0

[font.normal]
# style = "semibold"
style = "normal"
family = "Iosevka SS04"
#[keyboard]
#bindings = [
#  { key = "E", mods = "Control", action = "ReceiveChar" },
#]

[keyboard]
bindings = [
    { key = "E", mods = "Control", action = "ReceiveChar" }
]
# Font config:
#Font:
#    # Normal (roman)kk:
#    normal:
#        family: Liberation Mono
#        style: Regular
