#!/bin/bash
set -e
set -x

dconf write /org/gnome/desktop/wm/keybindings/minimize "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-left "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-left "['<Super>Left', '<Super>h']"
dconf write /org/gnome/mutter/keybindings/toggle-tiled-left "@as []"
dconf write /rg/gnome/settings-daemon/plugins/media-keys/screensaver "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-right "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-right "['<Super>Right', '<Super>l']"
dconf write /org/gnome/mutter/keybindings/toggle-tiled-right "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-left "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-left "['<Control><Super>Left']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-right "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-right "['<Control><Super>Right']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-left "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-left "['<Alt><Super>Left', '<Alt><Super>h']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-right "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-right "['<Alt><Super>Right', '<Alt><Super>l']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding "'<Super>t'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command "'alacritty'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name "'terminal'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
dconf write /org/gnome/desktop/wm/keybindings/toggle-maximized "@as []"
dconf write /org/gnome/desktop/wm/keybindings/maximize "@as []"
dconf write /org/gnome/desktop/wm/keybindings/toggle-maximized "['<Super>Up']"
dconf write /org/gnome/mutter/keybindings/toggle-tiled-left "['<Shift><Super>Left']"
dconf write /org/gnome/mutter/keybindings/toggle-tiled-right "['<Shift><Super>Right']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-1 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-1 "['<Super>1']"
dconf write /org/gnome/shell/keybindings/switch-to-application-1 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-2 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-2 "['<Super>2']"
dconf write /org/gnome/shell/keybindings/switch-to-application-2 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-3 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-3 "['<Super>3']"
dconf write /org/gnome/shell/keybindings/switch-to-application-3 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-4 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-4 "['<Super>4']"
dconf write /org/gnome/shell/keybindings/switch-to-application-4 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/begin-resize "@as []"
dconf write /org/gnome/desktop/wm/keybindings/begin-resize "['<Super>Down']"
dconf write /org/gnome/desktop/wm/keybindings/unmaximize "@as []"
