-- require("setup.plugin.telescope")
require("setup.plugin.treesitter")
require("setup.plugin.harpoon")
require("setup.plugin.undotree")
require("setup.plugin.lsp")
require("setup.plugin.oil")
require("setup.plugin.autoclose")
require("setup.plugin.mini")
require("setup.plugin.messenger")
require("setup.plugin.fff")
require("setup.plugin.vim-kitty-navigator")
require("setup.plugin.render-markdown")
require("setup.plugin.gruber-darker")
