#!/bin/bash
code --install-extension alefragnani.numbered-bookmarks
code --install-extension arzg.sema
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension eamodio.gitlens
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.github-vscode-theme
code --install-extension jasonliuuu.dark-breeze-color-scheme
code --install-extension johnpapa.vscode-peacock
code --install-extension jprestidge.theme-material-theme
code --install-extension magicstack.Chromodynamics
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Theme-1337
code --install-extension ms-vscode.Theme-MarkdownKit
code --install-extension pmndrs.pmndrs
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension cschlosser.doxdocgen
code --install-extension golang.go
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode.cmake-tools
code --install-extension twxs.cmake
code --install-extension zxh404.vscode-proto3
code --install-extension MichaelZhou.fleet-theme
